name: Build Android APK for Expo Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} 

    steps:
    - name: Checkout code
      run: git clone https://github.com/PoliNetworkOrg/PoliFemo.git

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install Eas
      run: npm install -g eas-cli

    - name: yarn
      run: corepack enable

    - name: pwd & ls
      run: |
        pwd
        ls -la

    - name: Install dependencies & Build APK
      run: |
        cd PoliFemo
        yarn
        eas build --platform android --local

    - name: Collect APK files
      run: |
        mkdir -p artifacts
        find . -name "*.apk" -exec mv {} artifacts/ \;

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk-artifacts
        path: artifacts/
        
