name: Build Android APK for Expo Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} 


    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/PoliNetworkOrg/PoliFemo.git
        cd PoliFemo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install Eas
      run: npm install -g eas-cli

    - name: yarn
      run: corepack enable

    - name: Install dependencies
      run: yarn

    - name: Build APK
      run: eas build --platform android --local

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: ./android/app/build/outputs/apk/release/app-release.apk
