name: Build Android APK for Expo Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} 

    steps:
    - name: Checkout code
      run: git clone https://github.com/PoliNetworkOrg/PoliFemo.git

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install Eas
      run: npm install -g eas-cli

    - name: yarn
      run: corepack enable

    - name: pwd & ls
      run: |
        pwd
        ls -la

    - name: Install dependencies & Build APK
      run: |
        cd PoliFemo
        yarn
        eas build --platform android --local

    - name: Collect APK files
      run: |
        mkdir -p artifacts
        find . -name "*.aab" -exec mv {} artifacts/ \;

    - name: Upload APK artifacts to action
      uses: actions/upload-artifact@v2
      with:
        name: apk-artifacts
        path: artifacts/

        
    - name: Create GitHub Release
      id: create_release
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_id=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/angeousta/PoliFemoReleases/releases" -d "{\"tag_name\":\"$tag\"}" | jq -r .id)
        echo "::set-output name=release_id::$release_id"
      shell: bash

    - name: Upload APK artifacts to release
      run: |
        release_id=${{ steps.create_release.outputs.release_id }}
        for file in artifacts/*.aab; do
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary "@$file" "https://uploads.github.com/repos/angeousta/PoliFemoReleases/releases/$release_id/assets?name=$(basename $file)"
        done
